language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - ./.travis_setup
env:
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.9,<1.10"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django>=1.7,<1.8"
script:
  - cd ./testproject; coverage run --source=phonenumber_field manage.py test phonenumber_field testapp
after_success:
  coveralls
